import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { QualityReportData } from './aggregator.js';

/**
 * Generate a markdown quality report from aggregated data.
 */
export function generateMarkdownReport(data: QualityReportData): string {
  const lines: string[] = [];

  lines.push('# VibeCheck Quality Report');
  lines.push('');
  lines.push(`Generated: ${new Date(data.generatedAt).toLocaleString()}`);
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total rule executions | ${data.totalHits} |`);
  lines.push(`| Blocks | ${data.blockWarnRatio.blocks} |`);
  lines.push(`| Warnings | ${data.blockWarnRatio.warns} |`);
  lines.push(`| Passes | ${data.blockWarnRatio.passes} |`);
  lines.push(`| Technical debt score | ${data.debtScore}/100 |`);
  lines.push('');

  // Debt score interpretation
  if (data.debtScore <= 10) {
    lines.push('> Excellent — very few issues detected.');
  } else if (data.debtScore <= 30) {
    lines.push('> Good — some issues but generally clean.');
  } else if (data.debtScore <= 60) {
    lines.push('> Fair — significant issues need attention.');
  } else {
    lines.push('> Poor — many violations detected. Review rule configuration.');
  }
  lines.push('');

  // Rule hit frequency
  if (data.ruleHits.length > 0) {
    lines.push('## Rule Hit Frequency');
    lines.push('');
    lines.push('| Rule | Hits | Blocks | Warns | Passes | Last Hit |');
    lines.push('|------|------|--------|-------|--------|----------|');

    for (const hit of data.ruleHits) {
      const lastHit = hit.lastHit ? new Date(hit.lastHit).toLocaleDateString() : '-';
      lines.push(
        `| \`${hit.ruleId}\` | ${hit.totalHits} | ${hit.blocks} | ${hit.warns} | ${hit.passes} | ${lastHit} |`,
      );
    }
    lines.push('');
  }

  // Most blocked rules
  const topBlocked = data.ruleHits.filter((h) => h.blocks > 0).slice(0, 5);
  if (topBlocked.length > 0) {
    lines.push('## Most Blocked Rules');
    lines.push('');
    lines.push('These rules block the most operations — consider whether they are too strict:');
    lines.push('');
    for (const hit of topBlocked) {
      lines.push(`- \`${hit.ruleId}\`: ${hit.blocks} blocks`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [VibeCheck](https://vibecheck.dev)*');

  return lines.join('\n');
}

/**
 * Save the markdown report to .vibecheck/reports/quality-report.md
 */
export async function saveReport(markdown: string, projectRoot: string): Promise<string> {
  const outputPath = join(projectRoot, '.vibecheck', 'reports', 'quality-report.md');
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, markdown, 'utf-8');
  return outputPath;
}
