import type { HookEvent, ResolvedConfig } from '../types.js';
import { getAllRules } from '../engine/registry.js';
import { serializeConfig } from '../config/compile.js';

/**
 * Generate a self-contained hook script that works without vibecheck installed.
 *
 * The bundled script embeds the resolved config and rule logic inline,
 * so it can run with just Node.js — no npm dependencies needed.
 */
export function bundleHookScript(event: HookEvent, config: ResolvedConfig): string {
  const serialized = serializeConfig(config);
  const allRules = getAllRules();

  // Collect enabled rules for this event
  const enabledRuleIds: string[] = [];
  for (const [ruleId, ruleConfig] of config.rules) {
    if (!ruleConfig.enabled) continue;
    const rule = allRules.get(ruleId);
    if (!rule) continue;
    if (!rule.events.includes(event)) continue;
    enabledRuleIds.push(ruleId);
  }

  return `#!/usr/bin/env node
// VibeCheck Ejected Hook — ${event}
// Generated by \`vibecheck eject\`. This script is self-contained.
// It does NOT require vibecheck to be installed.
//
// Rules: ${enabledRuleIds.join(', ') || 'none'}
// Generated: ${new Date().toISOString()}

const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

// Embedded resolved config
const CONFIG = ${JSON.stringify(serialized, null, 2)};

// Read stdin
let rawInput = '';
try { rawInput = fs.readFileSync(0, 'utf-8'); } catch {}
if (!rawInput) process.exit(0);

let data;
try { data = JSON.parse(rawInput); } catch { process.exit(0); }

const toolName = data.tool_name || '';
const toolInput = data.tool_input || {};
const filePath = toolInput.file_path || toolInput.path || '';

// Git context
function gitCmd(args, cwd) {
  try {
    return execSync('git ' + args, { cwd, timeout: 5000, encoding: 'utf-8' }).trim();
  } catch { return null; }
}

const repoRoot = filePath ? gitCmd('rev-parse --show-toplevel', path.dirname(filePath)) : null;
const branch = repoRoot ? gitCmd('branch --show-current', repoRoot) : null;

// Run rules
const issues = [];

${enabledRuleIds
  .map((id) => {
    const rule = allRules.get(id);
    if (!rule) return '';
    return generateInlineRuleCheck(id, rule.severity, event);
  })
  .filter(Boolean)
  .join('\n\n')}

// Output
if (issues.length > 0 && '${event}' === 'PreToolUse') {
  const blocking = issues.find(i => i.severity === 'block');
  if (blocking) {
    process.stderr.write('\\nBLOCKED by vibecheck [' + blocking.ruleId + ']\\n\\n' + blocking.message + '\\n');
    if (blocking.fix) process.stderr.write('\\nFix: ' + blocking.fix + '\\n');
    process.exit(2);
  }
  const warns = issues.filter(i => i.severity === 'warn');
  if (warns.length > 0) {
    const msg = warns.map(w => '[' + w.ruleId + '] ' + w.message).join('\\n');
    process.stdout.write(JSON.stringify({ continue: true, systemMessage: 'VibeCheck: ' + msg }));
  }
}
process.exit(0);
`;
}

function generateInlineRuleCheck(ruleId: string, severity: string, _event: HookEvent): string {
  // Generate simplified inline checks for common rules
  if (ruleId === 'security/branch-protection') {
    return `// ${ruleId}
if (['Edit', 'Write'].includes(toolName) && branch && ['main', 'master'].includes(branch.toLowerCase())) {
  issues.push({ ruleId: '${ruleId}', severity: '${severity}', message: "Cannot write on branch '" + branch + "'.", fix: 'Create a feature branch first.' });
}`;
  }

  if (ruleId === 'security/destructive-commands') {
    return `// ${ruleId}
if (toolName === 'Bash') {
  const cmd = toolInput.command || '';
  const dangerous = [
    [/rm\\s+-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*\\s+\\/(?!\\w)/, 'rm -rf /'],
    [/rm\\s+-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*\\s+~/, 'rm -rf ~'],
    [/git\\s+push\\s+.*--force(?!-with-lease)/, 'git push --force'],
    [/git\\s+reset\\s+--hard/, 'git reset --hard'],
  ];
  for (const [pat, name] of dangerous) {
    if (pat.test(cmd)) {
      issues.push({ ruleId: '${ruleId}', severity: '${severity}', message: 'Dangerous command: ' + name, fix: 'Run manually outside AI agent.' });
      break;
    }
  }
}`;
  }

  if (ruleId === 'security/secret-detection') {
    return `// ${ruleId}
if (toolName === 'Write') {
  const content = toolInput.content || '';
  const secrets = [
    [/AKIA[0-9A-Z]{16}/, 'AWS key'],
    [/gh[ps]_[A-Za-z0-9_]{36,}/, 'GitHub token'],
    [/sk_(?:live|test)_[A-Za-z0-9]{24,}/, 'Stripe key'],
    [/-----BEGIN (?:RSA |EC )?PRIVATE KEY-----/, 'Private key'],
  ];
  for (const [pat, name] of secrets) {
    if (pat.test(content)) {
      issues.push({ ruleId: '${ruleId}', severity: '${severity}', message: name + ' detected.', fix: 'Use environment variables.' });
      break;
    }
  }
}`;
  }

  // Generic fallback for other rules
  return `// ${ruleId} — not inlined (use vibecheck for full support)`;
}
