import type { Adapter, GeneratedFile, ResolvedConfig } from '../../types.js';
import { getAllRules } from '../../engine/registry.js';

/**
 * OpenCode adapter.
 *
 * Generates instructions.md with rule documentation.
 * Enforcement is ADVISORY only.
 */
export const openCodeAdapter: Adapter = {
  id: 'opencode',
  name: 'OpenCode',
  enforcement: 'advisory',

  async generate(config: ResolvedConfig): Promise<GeneratedFile[]> {
    const allRules = getAllRules();
    const lines: string[] = [
      '# VibeCheck Rules for OpenCode',
      '',
      '<!-- Generated by VibeCheck. Enforcement is advisory. -->',
      '<!-- For runtime enforcement, use Claude Code. -->',
      '',
      '## Active Rules',
      '',
    ];

    for (const [ruleId, ruleConfig] of config.rules) {
      if (!ruleConfig.enabled) continue;
      const rule = allRules.get(ruleId);
      if (!rule) continue;

      lines.push(`### ${rule.name} (\`${ruleId}\`)`);
      lines.push(`Severity: ${ruleConfig.severity}`);
      lines.push('');
      lines.push(rule.description);
      lines.push('');
    }

    return [
      {
        path: '.opencode/instructions.md',
        content: lines.join('\n'),
        mergeStrategy: 'overwrite',
      },
    ];
  },
};
