import type { Adapter, GeneratedFile, ResolvedConfig } from '../../types.js';
import { getAllRules } from '../../engine/registry.js';

/**
 * Codex adapter.
 *
 * Generates:
 * 1. AGENTS.md — comprehensive rule documentation
 * 2. .codex/config.toml — sandbox settings
 *
 * Enforcement is ADVISORY only.
 */
export const codexAdapter: Adapter = {
  id: 'codex',
  name: 'Codex',
  enforcement: 'advisory',

  async generate(config: ResolvedConfig): Promise<GeneratedFile[]> {
    const allRules = getAllRules();
    const files: GeneratedFile[] = [];

    // Build AGENTS.md
    const sections: string[] = [
      '# Project Coding Guidelines',
      '',
      '<!-- Generated by VibeCheck. Enforcement is advisory — -->',
      '<!-- these rules guide AI behavior but cannot block operations. -->',
      '<!-- For runtime enforcement, use Claude Code. -->',
      '',
    ];

    // Group rules by category
    const categories = new Map<string, Array<{ id: string; name: string; desc: string; severity: string }>>();

    for (const [ruleId, ruleConfig] of config.rules) {
      if (!ruleConfig.enabled) continue;
      const rule = allRules.get(ruleId);
      if (!rule) continue;

      const category = ruleId.split('/')[0];
      const existing = categories.get(category) ?? [];
      existing.push({
        id: ruleId,
        name: rule.name,
        desc: rule.description,
        severity: ruleConfig.severity,
      });
      categories.set(category, existing);
    }

    for (const [category, rules] of categories) {
      sections.push(`## ${capitalize(category)} Rules`);
      sections.push('');
      for (const rule of rules) {
        sections.push(`### ${rule.name}`);
        sections.push(`**ID:** \`${rule.id}\` | **Severity:** ${rule.severity}`);
        sections.push('');
        sections.push(rule.desc);
        sections.push('');
      }
    }

    files.push({
      path: 'AGENTS.md',
      content: sections.join('\n'),
      mergeStrategy: 'overwrite',
    });

    return files;
  },
};

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
