import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';

import '../../presets/index.js';
import '../../rules/index.js';

import { discoverConfigFile, readRawConfig } from '../../config/discovery.js';
import { resolveConfig } from '../../config/loader.js';
import { getAllPresets } from '../../config/presets.js';
import { serializeConfig } from '../../config/compile.js';
import { bundleHookScript } from '../../eject/bundler.js';
import type { VibeCheckConfig, HookEvent, ResolvedConfig } from '../../types.js';

const HOOK_EVENTS: HookEvent[] = ['PreToolUse', 'PostToolUse', 'Stop'];

export async function ejectCommand(): Promise<void> {
  const projectRoot = process.cwd();

  console.log('\n  VibeCheck Eject — Exporting standalone hooks...\n');
  console.log('  WARNING: After ejecting, hooks will NOT receive updates.');
  console.log('  You can safely remove vibecheck from dependencies.\n');

  // Load config
  const discovered = discoverConfigFile(projectRoot);
  if (!discovered) {
    console.error('  No vibecheck config found. Run `vibecheck init` first.');
    process.exit(1);
  }

  const rawConfig = await readRawConfig(discovered);
  const presetMap = getAllPresets();
  const resolvedConfig = resolveConfig(rawConfig as VibeCheckConfig, presetMap);

  // Generate bundled hook scripts
  for (const event of HOOK_EVENTS) {
    const script = bundleHookScript(event, resolvedConfig);
    const scriptPath = join(projectRoot, '.vibecheck', 'ejected', `vibecheck-${event.toLowerCase()}.js`);
    await mkdir(dirname(scriptPath), { recursive: true });
    await writeFile(scriptPath, script, 'utf-8');
    console.log(`  Created ${scriptPath}`);
  }

  // Save frozen config
  const serialized = serializeConfig(resolvedConfig);
  const configPath = join(projectRoot, '.vibecheck', 'ejected', 'frozen-config.json');
  await writeFile(configPath, JSON.stringify(serialized, null, 2), 'utf-8');
  console.log(`  Created ${configPath}`);

  // Generate eject readme
  const readmePath = join(projectRoot, '.vibecheck', 'ejected', 'VIBECHECK-EJECTED.md');
  await writeFile(readmePath, generateEjectReadme(resolvedConfig), 'utf-8');
  console.log(`  Created ${readmePath}`);

  console.log('\n  Ejected successfully.');
  console.log('  Update .claude/settings.json to point to .vibecheck/ejected/ scripts.');
  console.log('  You can now remove vibecheck from your dependencies.\n');
}

function generateEjectReadme(config: ResolvedConfig): string {
  const ruleCount = Array.from(config.rules.values()).filter((r) => r.enabled).length;
  return `# VibeCheck — Ejected Hooks

These hook scripts were generated by \`vibecheck eject\` and are **self-contained**.
They do not require the \`vibecheck\` npm package to run.

## What was exported

- **${ruleCount} active rules** bundled into standalone hook scripts
- **Frozen config** snapshot in \`frozen-config.json\`

## How to use

Update your \`.claude/settings.json\` hooks to point to these scripts:

\`\`\`json
{
  "hooks": {
    "PreToolUse": [{
      "hooks": [{ "type": "command", "command": "node .vibecheck/ejected/vibecheck-pretooluse.js" }],
      "matcher": "Edit|Write|Bash"
    }]
  }
}
\`\`\`

## Maintenance

These scripts are frozen — they will NOT receive updates when new VibeCheck versions
are released. To get updates, re-install vibecheck and run \`vibecheck eject\` again.

## Generated

${new Date().toISOString()}
`;
}
